#!/usr/bin/env python3
"""Replace US-0120 discovery block in po_to_tl.md."""
import codecs

path = r'c:\flowGit\sonstiges\gsd_cursor\handoffs\po_to_tl.md'

with open(path, 'rb') as f:
    raw = f.read()

marker = b'## Discovery handoff'
idx2 = raw.find(marker, 10)  # Second occurrence = US-0119 block

# Build block as bytes directly using latin-1 encoding
# The em-dash character (U+2014) in UTF-8 is E2 80 94
# But let's just use a simple -> arrow (ASCII safe)
NEW_BLOCK = (
    b'## Discovery handoff -> US-0120 Separate `/closure` phase after `/release` (spec macro)\r\n'
    b'\r\n'
    b'**Phase completed**: discovery\r\n'
    b'**Phase role**: po\r\n'
    b'**Story**: US-0120 Separate `/closure` phase after `/release` with exclusive Story Closure responsibility\r\n'
    b'**Verdict**: PASS (no DECISION_GATE)\r\n'
    b'**Timestamp**: 2026-07-06T21:30:00Z\r\n'
    b'**Fresh context marker**: po-US0120-discovery-20260706T213000Z-fresh\r\n'
    b'**Runtime proof**: rp-auto-20260706-01-discovery-PO-20260706T213000Z-US-0120 (proof_hash=447f401d9ca72415e0f3d607829eaced5fb14cbbffd71a48a336de48a9d040dd, proof_ttl=2026-07-06T22:30:00Z)\r\n'
    b'**Delivery mode**: ultra_lean (spec+plan merged)\r\n'
    b'**Macro phase**: spec (intake+discovery merged)\r\n'
    b'**Companion DEC**: none (modifies DEC-0052 + DEC-0082 directly)\r\n'
    b'**Work kind**: doc\r\n'
    b'**Plan area**: lifecycle-governance\r\n'
    b'\r\n'
    b'### Summary\r\n'
    b'\r\n'
    b'Extract Story Closure (Status DONE in backlog.md + acceptance checkbox + state checkpoint + closure-verification artifact) from /release step 10-12 into a dedicated /closure phase with exclusive qe role ownership. New ultra_lean ship macro: release -> closure -> refresh-context (3 phases). Orchestrator post-closure rg verification (D12) ensures materialization fidelity (fixes US-0119 closure-l\xfccke pattern). Compose (read-only) with US-0043/US-0045/US-0040/US-0048/US-0056/US-0096.\r\n'
    b'\r\n'
    b'### Discovery locks (D1..D12)\r\n'
    b'\r\n'
    b'**D1 (phase ownership)**: /closure phase role = qe (fresh qe subagent per BUG-0006 / US-0048 isolation). Fallback: curator when qe unavailable.\r\n'
    b'\r\n'
    b'**D2 (phase ordering)**: /closure executes AFTER /release PASS (release artifacts written, queue updated), BEFORE /refresh-context. Ultra_lean ship macro becomes release -> closure -> refresh-context (3 phases). Standard: ... -> execute -> qa -> verify-work -> release -> closure -> refresh-context. All 3 delivery modes (standard, ultra_lean, mega_quick) include closure.\r\n'
    b'\r\n'
    b'**D3 (input prerequisites)**: /closure requires (a) release queue row status=released, (b) handoffs/releases/Sxxxx-release-notes.md EXISTS with PASS verdict, (c) sprints/Sxxxx/qa-findings.md EXISTS. Fail-gated: CLOSURE_RELEASE_EVIDENCE_MISSING.\r\n'
    b'\r\n'
    b'**D4 (output artifacts)**: (a) docs/product/backlog.md target story status OPEN -> DONE (canonical ownership per US-0045), (b) docs/product/acceptance.md target checkbox [ ] -> [x] (derived view per US-0045), (c) docs/engineering/state.md closure checkpoint (derived view per US-0045), (d) sprints/Sxxxx/closure-verification.json NEW artifact documenting closure execution with isolation evidence + runtime proof references.\r\n'
    b'\r\n'
    b'**D5 (compose with US-0043)**: /closure is the executor of backlog reconciliation that US-0043 defines. US-0043 contract UNCHANGED; closure implements it as a dedicated phase. Evidence precedence: release queue -> release notes -> qa-findings -> uat -> release-findings.\r\n'
    b'\r\n'
    b'**D6 (compose with US-0045)**: /closure follows US-0045 canonical status ownership: backlog.md is canonical owner (mutated FIRST); acceptance.md and state.md are derived views (mutated SECOND, atomically). Contradiction -> CANONICAL_STATUS_CONFLICT fail-gate.\r\n'
    b'\r\n'
    b'**D7 (compose with US-0040)**: /closure operates AFTER release artifacts are written (US-0040 contract). Release writes release notes + queue; closure writes status/acceptance. No overlap.\r\n'
    b'\r\n'
    b'**D8 (compose with US-0048)**: /closure produces its own isolation evidence entry in state.md per US-0048 (phase_id=closure, role=qe, fresh_context_marker, timestamp). Fresh qe subagent per BUG-0006.\r\n'
    b'\r\n'
    b'**D9 (compose with US-0056)**: /closure produces its own strict runtime proof per US-0056 (sorted-key JSON payload, SHA-256 proof_hash, proof_ttl_seconds=3600). Per DEC-0038.\r\n'
    b'\r\n'
    b'**D10 (release.md step 10-12 removal)**: After US-0120 ships, .cursor/commands/release.md steps 10-12 are REMOVED and replaced with a pointer: "Backlog reconciliation is now handled by the dedicated /closure phase -- see .cursor/commands/closure.md".\r\n'
    b'\r\n'
    b'**D11 (template parity)**: New .cursor/commands/closure.md must be byte-identical to template/.cursor/commands/closure.md (active <-> template mirror). Checked by check_intake_template_parity.py.\r\n'
    b'\r\n'
    b'**D12 (orchestrator post-closure verification)**: After /closure returns, orchestrator runs direct rg verification: (a) rg "^- Status: DONE$" docs/product/backlog.md (target story block), (b) rg "^\\*- \\[x\\] US-xxxx:" docs/product/acceptance.md (target row). If either FAIL -> escalate to operator with CLOSURE_VERIFICATION_FAILED.\r\n'
    b'\r\n'
    b'### Composition notes\r\n'
    b'\r\n'
    b'**Compose, do not amend (6/6 UNCHANGED)**: US-0043 (backlog reconciliation contract), US-0045 (canonical status source), US-0040 (release artifacts), US-0048 (isolation evidence), US-0056 (runtime proof), US-0096 (delivery modes). All verified present (read-only consumers of US-0120).\r\n'
    b'\r\n'
    b'**DC check**: `grep "^## US-0120" docs/engineering/architecture.md` -> no matches (expected; anchor will be added in /architecture phase).\r\n'
    b'\r\n'
    b'### Open questions for /research (Q1..Q10)\r\n'
    b'\r\n'
    b'**Q1** (closure-verification artifact schema): exact fields, required vs optional, format (.json vs .md).\r\n'
    b'**Q2** (closure role designation): qe by default, fallback to curator; canonical choice confirmation.\r\n'
    b'**Q3** (phase->role matrix extension): DEC-0052 closure row placement, role column syntax.\r\n'
    b'**Q4** (drain hook in-flight story detection): /auto drain-advance hook detects stories that completed /release but skipped closure (status still OPEN) -> spawn /closure.\r\n'
    b'**Q5** (backward compat for status-drift stories): US-0108 etc. -- forward-compat only, no retroactive closure.\r\n'
    b'**Q6** (template parity scope): .cursor/commands/closure.md <-> template/.cursor/commands/closure.md byte-identical enforcement.\r\n'
    b'**Q7** (orchestrator rg verification regex): exact patterns for post-closure verification.\r\n'
    b'**Q8** (release.md step renumbering): after removing steps 10-12, renumber remaining steps 13+ -> 10+.\r\n'
    b'**Q9** (compose surface verification): 6 architectural anchors present and unchanged.\r\n'
    b'**Q10** (test coverage): 10 contract tests in tests/us0120_closure_phase_test.py.\r\n'
    b'\r\n'
    b'### Risks carried to /architecture (R1..R6)\r\n'
    b'\r\n'
    b'**R1 (MEDIUM)**: Subagent execution fidelity (US-0119 pattern -- release subagent claimed closure but files unchanged). Mitigated by orchestrator-side post-closure rg verification (D12).\r\n'
    b'\r\n'
    b'**R2 (MEDIUM)**: Backward compat for in-flight stories (stories currently in /release when US-0120 ships). Detection logic in /auto drain hook (Q4) must handle both cases (closure already performed vs skipped).\r\n'
    b'\r\n'
    b'**R3 (LOW-MEDIUM)**: DEC-0052 phase->role matrix scope creep. Only ADD closure:qe row; must NOT modify existing role mappings.\r\n'
    b'\r\n'
    b'**R4 (LOW-MEDIUM)**: DEC-0082 delivery-mode table scope creep. Only ADD closure to ship macro; must NOT modify other macro definitions.\r\n'
    b'\r\n'
    b'**R5 (LOW)**: release.md step 10-12 removal scope. Only remove closure responsibilities; must NOT modify other release steps.\r\n'
    b'\r\n'
    b'**R6 (LOW)**: Template parity drift. .cursor/commands/closure.md active <-> template must stay byte-identical across all future edits.\r\n'
    b'\r\n'
    b'### Isolation evidence\r\n'
    b'\r\n'
    b'- phase_id=discovery, role=po, story_id=US-0120, sprint_id=S0120\r\n'
    b'- orchestrator_run_id=auto-20260706-01\r\n'
    b'- fresh_context_marker=po-US0120-discovery-20260706T213000Z-fresh\r\n'
    b'- timestamp=2026-07-06T21:30:00Z (UTC)\r\n'
    b'- evidence_ref=docs/product/backlog.md (US-0120 block L3972-4038), docs/product/acceptance.md (US-0120 row L146), handoffs/intake_evidence/US-0120-intake-20260706.json (full read), handoffs/po_to_tl.md (current US-0120 block L1-59 narrow-read), docs/engineering/state.md (US-0118 discovery checkpoint L84-107 narrow-read, US-0119 discovery checkpoint L121-176 narrow-read), .cursor/commands/release.md (steps 10-12 L334-347 narrow-read for D10 removal scope; release gate chain L88-101; backlog reconciliation contract L148-168; canonical status source L169-188), docs/engineering/architecture.md (grep ^## US-0043/^## US-0045/^## US-0040/^## US-0096/^## US-0048/^## US-0056 anchors only -- all 6 verified present), decisions/DEC-0052.md (phase->role matrix), decisions/DEC-0082.md (ship macro table)\r\n'
    b'- PO subagent spawned fresh per BUG-0006 / US-0048 isolation; no prior chat history carried forward; no MCP / browser / shell side-effects beyond narrow-read grep + read tool calls + the artifact writes listed in this prompt. No .env reads, no credentials access, no intake-evidence mutation.\r\n'
    b'\r\n'
    b'### Strict runtime proof\r\n'
    b'\r\n'
    b'- runtime_proof_id=rp-auto-20260706-01-discovery-PO-20260706T213000Z-US-0120\r\n'
    b'- Canonical payload (sorted-key JSON per DEC-0038): {"orchestrator_run_id":"auto-20260706-01","phase_id":"discovery","proof_issued_at":"2026-07-06T21:30:00Z","proof_ttl_seconds":3600,"role":"po","runtime_proof_id":"rp-auto-20260706-01-discovery-PO-20260706T213000Z-US-0120","sprint_id":"S0120","story_id":"US-0120"}\r\n'
    b'- proof_hash=447f401d9ca72415e0f3d607829eaced5fb14cbbffd71a48a336de48a9d040dd (SHA-256, python hashlib)\r\n'
    b'- proof_ttl_seconds=3600, proof_ttl=2026-07-06T22:30:00Z (UTC)\r\n'
    b'\r\n'
    b'### Decision gate + next scheduled phase\r\n'
    b'\r\n'
    b'- decision_gate=false (no DECISION_GATE)\r\n'
    b'- next_scheduled_phase=/research (role=tech-lead per US-0069 / DEC-0051)\r\n'
    b'- stop_condition=STOP after discovery completes; hand off via artifacts only to /research in fresh tech-lead subagent (BUG-0006)\r\n'
    b'\r\n'
    b'---\r\n'
    b'\r\n'
)

new_raw = NEW_BLOCK + raw[idx2:]

with open(path, 'wb') as f:
    f.write(new_raw)

print('SUCCESS. Old size:', len(raw), 'New size:', len(new_raw))
print('Old US-0120 block removed:', idx2, 'bytes')
